bind / split-window -h
bind - split-window -v

#bind-key a send-prefix

set-option -g status-style bg=colour235,fg=gray,dim
set-window-option -g window-status-style fg=gray,bg=colour236,dim

set -g pane-active-border-style bg=default,fg=blue
set -g pane-border-style fg=black

set -g update-environment -r

set -g status-right '#H'

set -g pane-border-status top
set -g pane-border-format " [ ###P  #T ] "

set-hook -g after-split-window 'selectp -T ""'
set-hook -g after-new-window 'selectp -T ""'
set-hook -g after-new-session 'selectp -T ""'

bind-key . command-prompt -I "#{pane_title}" -p "Pane title:" 'select-pane -T "%%"'

set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'
set -g allow-rename off
